theme: jekyll-theme-minimal
title: Denise Braithwaite
description: Bookmark this to keep an eye on my resume, contact information, and project updates!
url: "https://denise-b076.github.io"
baseurl: ""
